### ISSUE TITLE
@pawaitemadisoncollege Api Exercise is done.

### ISSUE THREAD

**Issue by GuruKatuwal** [GuruKatuwal/BillingSystem#11]
@pawaitemadisoncollege  Api Exercise is done.

**Comment by pawaitemadisoncollege** [comment]
You have a good start implementing the Zippo api here, @GuruKatuwal.

A few things that are probably on your radar already, but I wanted to list them here just so we don't lose track of them!

- [ ] Put the base url for any api calls in a properties file rather than hardcoding it: https://github.com/GuruKatuwal/BillingSystem/blob/90095b11eced5e0bbce3f00866f235ae4935380c/src/main/java/BillingSystem/persistence/ZippoDao.java#L39
- [ ] Update the `getCountry` method to accept a zip code as a parameter so is more flexible. https://github.com/GuruKatuwal/BillingSystem/blob/90095b11eced5e0bbce3f00866f235ae4935380c/src/main/java/BillingSystem/persistence/ZippoDao.java#L36-L39
- [ ] Make sure javadoc make sense for a given class or method. https://github.com/GuruKatuwal/BillingSystem/blob/90095b11eced5e0bbce3f00866f235ae4935380c/src/main/java/BillingSystem/persistence/ZippoDao.java#L31-L36
- [ ] Is there a worldwide postal code api that would make sense to use for your application, since your target audience is not us based?
- [ ] Remember to update your time log - looks like the last entry was 10/5?
