### ISSUE TITLE
finaly done with check point.

### ISSUE THREAD

**Issue by GuruKatuwal** [GuruKatuwal/BillingSystem#12]
@pawaitemadisoncollege  Done with checkpoint #3. I don't know what I struggle with but it took me a lot of time.

**Comment by pawaitemadisoncollege** [comment]
Hi @GuruKatuwal, a few things for Checkpoint 3:

- [x] I'm not able to access your application in AWS right now - my guess is that the ec2 instance just needs to be bounced (sent you a message in slack.
- [x] time log formatting still doesn't show in github as a table... Here's a reference that might help: https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/organizing-information-with-tables
- [x] See below for a couple questions about the readme.md 
![Screen Shot 2020-11-05 at 8 26 38 AM](https://user-images.githubusercontent.com/13874466/98253954-4bcd1980-1f41-11eb-98ee-e7e4c3bed544.png)
- [ ] Is the UserDao necessary anymore? It looks like you've converted over to the GenericDao, so UserDao can be removed?
- [ ] use .equals to compare the entire user object rather than two instance variables. https://github.com/GuruKatuwal/BillingSystem/blob/ae8dbebe1428f697ec372bc1675a001eea3b2d0f/src/test/java/BillingSystem/persitence/UserDaoTest.java#L67-L68 
Refer to the video Comparing Hibernate Entities with equals in week 5 for more detail.
